-- First-party website analytics, Phase 2a (collection).
-- Additive only: no backfill, no startup DDL, no change to existing tables.
-- Plan: docs/superpowers/plans/2026-10-03-analytics-page.md (Phase 2) and
-- docs/superpowers/plans/2026-10-02-first-party-analytics-revised.md §4, §7.
-- Retention (raw events 90 days, sessions 25 months) runs from the Phase 2c job.
begin;

create table public.analytics_sessions (
  id uuid primary key,                                  -- ms_sid cookie, random per visit
  org_id uuid not null,
  visitor_id uuid not null,                             -- ms_vid cookie, random per browser
  started_at timestamptz not null,
  last_seen_at timestamptz not null,
  is_new_visitor boolean not null default true,
  entry_path text not null constraint analytics_sessions_entry_path_check check (char_length(entry_path) between 1 and 200 and left(entry_path, 1) = '/'),
  referrer_host text constraint analytics_sessions_referrer_host_check check (char_length(referrer_host) <= 100),
  source text not null constraint analytics_sessions_source_check check (char_length(source) between 1 and 100),
  medium text not null constraint analytics_sessions_medium_check check (char_length(medium) between 1 and 100),
  utm_source text constraint analytics_sessions_utm_source_check check (char_length(utm_source) <= 100),
  utm_medium text constraint analytics_sessions_utm_medium_check check (char_length(utm_medium) <= 100),
  utm_campaign text constraint analytics_sessions_utm_campaign_check check (char_length(utm_campaign) <= 100),
  utm_content text constraint analytics_sessions_utm_content_check check (char_length(utm_content) <= 100),
  utm_term text constraint analytics_sessions_utm_term_check check (char_length(utm_term) <= 100),
  device text not null default 'unknown' constraint analytics_sessions_device_check check (device in ('mobile', 'tablet', 'desktop', 'unknown')),
  country text constraint analytics_sessions_country_check check (char_length(country) <= 80),
  city text constraint analytics_sessions_city_check check (char_length(city) <= 80),
  pageviews integer not null default 0 constraint analytics_sessions_pageviews_check check (pageviews >= 0),
  product_views integer not null default 0 constraint analytics_sessions_product_views_check check (product_views >= 0),
  engaged_seconds integer not null default 0 constraint analytics_sessions_engaged_seconds_check check (engaged_seconds between 0 and 86400),
  cart_at timestamptz,
  checkout_at timestamptz,
  purchase_signal_at timestamptz,
  constraint analytics_sessions_org_id_key unique (org_id, id),
  constraint analytics_sessions_seen_after_start check (last_seen_at >= started_at)
);
create index analytics_sessions_org_started_idx on public.analytics_sessions (org_id, started_at desc);
create index analytics_sessions_org_visitor_idx on public.analytics_sessions (org_id, visitor_id, started_at);

create table public.analytics_events (
  id bigint generated always as identity primary key,
  org_id uuid not null,
  event_id uuid not null,                               -- generated by the tracker; retries reuse it
  session_id uuid not null,
  visitor_id uuid not null,
  kind text not null constraint analytics_events_kind_check check (kind in ('page_view', 'cart', 'checkout', 'purchase_signal', 'engage')),
  path text not null constraint analytics_events_path_check check (char_length(path) between 1 and 200 and left(path, 1) = '/'),
  product_slug text constraint analytics_events_product_slug_check check (product_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(product_slug) <= 120),
  active_seconds integer not null default 0 constraint analytics_events_active_seconds_check check (active_seconds between 0 and 1800),
  received_at timestamptz not null,
  constraint analytics_events_org_event_key unique (org_id, event_id),
  constraint analytics_events_session_fkey foreign key (org_id, session_id) references public.analytics_sessions (org_id, id) on delete cascade
);
create index analytics_events_org_received_idx on public.analytics_events (org_id, received_at desc);
create index analytics_events_org_session_idx on public.analytics_events (org_id, session_id);

create table public.analytics_session_pages (
  org_id uuid not null,
  session_id uuid not null,
  path text not null constraint analytics_session_pages_path_check check (char_length(path) between 1 and 200 and left(path, 1) = '/'),
  views integer not null default 1 constraint analytics_session_pages_views_check check (views > 0),
  is_entry boolean not null default false,
  first_seen_at timestamptz not null,
  primary key (session_id, path),
  constraint analytics_session_pages_session_fkey foreign key (org_id, session_id) references public.analytics_sessions (org_id, id) on delete cascade
);
create index analytics_session_pages_org_path_idx on public.analytics_session_pages (org_id, path);

create table public.analytics_session_products (
  org_id uuid not null,
  session_id uuid not null,
  product_slug text not null constraint analytics_session_products_slug_check check (product_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(product_slug) <= 120),
  views integer not null default 1 constraint analytics_session_products_views_check check (views > 0),
  first_seen_at timestamptz not null,
  primary key (session_id, product_slug),
  constraint analytics_session_products_session_fkey foreign key (org_id, session_id) references public.analytics_sessions (org_id, id) on delete cascade
);
create index analytics_session_products_org_slug_idx on public.analytics_session_products (org_id, product_slug);

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_session_pages enable row level security;
alter table public.analytics_session_products enable row level security;
-- No browser policies. Explicit least-privilege grants also override project defaults.
-- Retention deletes are granted with the Phase 2c job, not here.
revoke all on public.analytics_sessions, public.analytics_events, public.analytics_session_pages, public.analytics_session_products
  from public, anon, authenticated, service_role;
grant select, insert, update on public.analytics_sessions, public.analytics_session_pages, public.analytics_session_products to service_role;
grant select, insert on public.analytics_events to service_role;

-- Records one validated tracker hit atomically. The caller (Express, service
-- role) has already resolved the fixed workspace, filtered bots and validated
-- ids/paths. Returns 'recorded', 'duplicate' (retry of a stored event),
-- 'expired' (session idle > 30 min; the tracker starts a new one) or
-- 'rejected' (session id belongs to another workspace).
create function public.record_analytics_hit(
  p_org_id uuid,
  p_event_id uuid,
  p_session_id uuid,
  p_visitor_id uuid,
  p_kind text,
  p_path text,
  p_product_slug text,
  p_active_seconds integer,
  p_received_at timestamptz,
  p_entry jsonb
) returns text language plpgsql security invoker set search_path = '' as $$
declare
  existing public.analytics_sessions%rowtype;
  inserted_event bigint;
  first_page boolean;
begin
  if p_org_id is null or p_event_id is null or p_session_id is null or p_visitor_id is null or p_received_at is null then
    raise exception 'record_analytics_hit: missing required argument';
  end if;

  select * into existing from public.analytics_sessions where id = p_session_id for update;
  if found and existing.org_id <> p_org_id then
    return 'rejected';
  end if;
  if found and existing.last_seen_at < p_received_at - interval '30 minutes' then
    return 'expired';
  end if;

  if not found then
    -- An engagement flush or step cannot open a visit on its own.
    if p_kind <> 'page_view' then
      return 'expired';
    end if;
    insert into public.analytics_sessions (
      id, org_id, visitor_id, started_at, last_seen_at, is_new_visitor, entry_path, referrer_host, source, medium,
      utm_source, utm_medium, utm_campaign, utm_content, utm_term, device, country, city
    ) values (
      p_session_id, p_org_id, p_visitor_id, p_received_at, p_received_at,
      not exists (select 1 from public.analytics_sessions s where s.org_id = p_org_id and s.visitor_id = p_visitor_id),
      p_path, p_entry->>'referrer_host', coalesce(p_entry->>'source', 'direct'), coalesce(p_entry->>'medium', 'none'),
      p_entry->>'utm_source', p_entry->>'utm_medium', p_entry->>'utm_campaign', p_entry->>'utm_content', p_entry->>'utm_term',
      coalesce(p_entry->>'device', 'unknown'), p_entry->>'country', p_entry->>'city'
    )
    on conflict (id) do nothing;
    select * into existing from public.analytics_sessions where id = p_session_id for update;
    if existing.org_id <> p_org_id then
      return 'rejected';
    end if;
  end if;

  insert into public.analytics_events (org_id, event_id, session_id, visitor_id, kind, path, product_slug, active_seconds, received_at)
  values (p_org_id, p_event_id, p_session_id, p_visitor_id, p_kind, p_path, p_product_slug, coalesce(p_active_seconds, 0), p_received_at)
  on conflict (org_id, event_id) do nothing
  returning id into inserted_event;
  if inserted_event is null then
    return 'duplicate';
  end if;

  first_page := existing.pageviews = 0;
  update public.analytics_sessions set
    last_seen_at = greatest(last_seen_at, p_received_at),
    pageviews = pageviews + (p_kind = 'page_view')::int,
    product_views = product_views + (p_kind = 'page_view' and p_product_slug is not null)::int,
    engaged_seconds = least(86400, engaged_seconds + case when p_kind = 'engage' then coalesce(p_active_seconds, 0) else 0 end),
    cart_at = case when p_kind = 'cart' then coalesce(cart_at, p_received_at) else cart_at end,
    checkout_at = case when p_kind = 'checkout' then coalesce(checkout_at, p_received_at) else checkout_at end,
    purchase_signal_at = case when p_kind = 'purchase_signal' then coalesce(purchase_signal_at, p_received_at) else purchase_signal_at end
  where id = p_session_id;

  if p_kind = 'page_view' then
    insert into public.analytics_session_pages (org_id, session_id, path, views, is_entry, first_seen_at)
    values (p_org_id, p_session_id, p_path, 1, first_page, p_received_at)
    on conflict (session_id, path) do update set views = public.analytics_session_pages.views + 1;
    if p_product_slug is not null then
      insert into public.analytics_session_products (org_id, session_id, product_slug, views, first_seen_at)
      values (p_org_id, p_session_id, p_product_slug, 1, p_received_at)
      on conflict (session_id, product_slug) do update set views = public.analytics_session_products.views + 1;
    end if;
  end if;
  return 'recorded';
end;
$$;

revoke all on function public.record_analytics_hit(uuid, uuid, uuid, uuid, text, text, text, integer, timestamptz, jsonb) from public, anon, authenticated;
grant execute on function public.record_analytics_hit(uuid, uuid, uuid, uuid, text, text, text, integer, timestamptz, jsonb) to service_role;

commit;
